### ISSUE TITLE
Plan for releasing the preprocessing code

### ISSUE THREAD

**Issue by lxxue** [andrewsonga/Total-Recon#6]
Hi Andrew,

Thank you for the great work and the detailed experiments.

I want to try out some experiments with my own RGBD videos. I wonder if you have any timeline for the preprocessing code release?

**Comment by andrewsonga** [comment]
Hello,

thank you for your interest in and kind words about our project!
I am planning to work on the preprocessing code over this weekend.
I expect to be able to release it before the end of the month.

Out of curiosity, were your RGBD videos captured with the Record3D app on the iPhone / iPad Pro? 
The reason I am asking is because, the codebase and the soon-to-be-released preprocessing code assume that the data was captured with the Record3D app and follow its formatting conventions.

**Comment by lxxue** [comment]
Thanks for the quick reply. I am looking forward to it!

Yes my video is captured with the Record3D app on an iPhone

**Comment by andrewsonga** [comment]
The preprocessing code for user-provided RGBD videos has been released. Thank you for your patience!
